import java.lang.reflect.Method
import java.nio.file.Files
import java.util.concurrent.TimeUnit
import java.util.jar.JarEntry
import java.util.jar.JarFile

plugins {
	id 'java'
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
	id 'net.neoforged.moddev' version '2.0.42-beta'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets {
	main {
		java {
			srcDirs = ['src/main/java'] + Arrays.asList(file("src/main/versions/${project.minecraft_version}/java").listFiles())
		}
		resources {
			srcDirs = Arrays.asList(file("src/main/versions/${project.minecraft_version}/resources").listFiles())
		}
	}
}

repositories {
	mavenLocal() //AutoCodec

	maven {
		name = 'Modrinth'
		url = 'https://api.modrinth.com/maven'
		content {
			includeGroup 'maven.modrinth'
		}
	}

	//manifold
	maven {
		url = 'https://oss.sonatype.org/content/repositories/snapshots/'
	}

	maven {
		name = 'Sponge / Mixin'
		url = 'https://repo.spongepowered.org/repository/maven-public/'
	}
}

neoForge {
	version = project.neo_version

	parchment {
		mappingsVersion = project.parchment_mappings_version
		minecraftVersion = project.parchment_minecraft_version
	}

	runs {
		client {
			client()
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		server {
			server()
			programArgument '--nogui'
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		gameTestServer {
			type = "gameTestServer"
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		data {
			data()
			programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
		}
	}

	mods {
		"${project.mod_id}" {
			sourceSet sourceSets.main
		}
	}
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
	testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	String AUTO_CODEC_VERSION = '6.0.2'
	implementation("builderb0y:autocodec:$AUTO_CODEC_VERSION") {
		transitive = false //don't include different version of DFU than what minecraft uses.
	}
	jarJar("builderb0y:autocodec:$AUTO_CODEC_VERSION") {
		transitive = false
	}

	annotationProcessor 'systems.manifold:manifold-preprocessor:2025.1.27'
}

compileJava {
	options.compilerArgs.add('-Xplugin:Manifold')
}

processResources {
	var replaceProperties = [
		mod_id: project.mod_id,
		mod_name: project.mod_name,
		mod_license: project.mod_license,
		mod_version: project.mod_version,
		mod_authors: project.mod_authors,
		mod_description: project.mod_description,
		neoforge_version_range: project.neoforge_version_range,
		minecraft_version_range: project.minecraft_version_range,
		loader_version_range: project.loader_version_range
	]
	inputs.properties replaceProperties
	filteringCharset 'UTF-8'

	filesMatching(['META-INF/neoforge.mods.toml']) {
		expand replaceProperties
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.compilerArgs.add('-parameters')
}

jar {
	exclude 'assets/bigglobe/icon_1440x.png'
	exclude 'assets/bigglobe/icon_256x_pride.gif'
}

test {
	useJUnitPlatform()
}

tasks.register('copyToReleases', Copy) {
	dependsOn(jar)
	from("$projectDir/build/libs") {
		include("$project.archives_base_name-${project.version}.jar")
		rename {
			"$project.archives_base_name-$project.version-MC${minecraft_version}-neoforge.jar"
		}
	}
	into(file("releases/${project.version.toString().replace('.' as char, '/' as char)}"))
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}

publishing {
	publications {
		register('mavenJava', MavenPublication) {
			from components.java
		}
	}
	repositories {
		maven {
			url "file://${project.projectDir}/mcmodsrepo"
		}
	}
}