# Project settings
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true

# Mod properties
mod_id=bigglobe
mod_name=Big Globe
mod_license=CC-BY-NC 4.0
mod_version=5.2.1
mod_authors=Builderb0y
mod_description=Round earth is a hoax invented by Big Globe to sell more globes!
maven_group=builderb0y
archives_base_name=bigglobe

# Minecraft properties
minecraft_version=1.21.1
neo_version=21.1.77
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

# Dependency version ranges
neoforge_version_range=[21.1,)
minecraft_version_range=[1.21,1.21.1]
loader_version_range=[4,)
